# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 480d3e3c49e7bd3277f4acb0e6d0082c3e61ebcf553963e0a5ef3d91fb940def48c048376c59f52ec9080748a211e28e441eea1dd878d672b35a50f84e98a4e7

test:
  secret_key_base: 74d78a6f47d432c65a2ac2f3edca5057f514a5738690b477930d27540a520889e01328218caf20ecb698c68359618201a98b15bf3b7c6ccb6d09089c957b5701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
